apps:bot:
  - "### Which (application|package|application or package) is this (bug
    report|feature request) for\\?\\n\\nbot\\n"
packages:database:
  - "### Which (application|package|application or package) is this (bug
    report|feature request) for\\?\\n\\ndatabase\\n"
packages:logger:
  - "### Which (application|package|application or package) is this (bug
    report|feature request) for\\?\\n\\nlogger\\n"
packages:tesseract:
  - "### Which (application|package|application or package) is this (bug
    report|feature request) for\\?\\n\\ntesseract\\n"
