apps:bot:
  - "### Which (application|package|application or package) is this (bug
    report|feature request) for\\?\\n\\nbot\\n"
apps:website:
  - "### Which (application|package|application or package) is this (bug
    report|feature request) for\\?\\n\\nwebsite\\n"
packages:database:
  - "### Which (application|package|application or package) is this (bug
    report|feature request) for\\?\\n\\ndatabase\\n"
packages:logger:
  - "### Which (application|package|application or package) is this (bug
    report|feature request) for\\?\\n\\nlogger\\n"
packages:tesseract:
  - "### Which (application|package|application or package) is this (bug
    report|feature request) for\\?\\n\\ntesseract\\n"
packages:ui:
  - "### Which (application|package|application or package) is this (bug
    report|feature request) for\\?\\n\\nui\\n"
packages:utils:
  - "### Which (application|package|application or package) is this (bug
    report|feature request) for\\?\\n\\nutils\\n"
