name: Bug report
description: Report incorrect or unexpected behavior
labels: [bug, need repro]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for filing an issue! If you are here to ask a question, use Discord instead: https://discord.gg/FD5MMabf8Y

        This issue form is for Elvia, including other packages.
  - type: dropdown
    id: package
    attributes:
      label: Which package is this bug report for?
      options:
        - bot
        - database
        - logger
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Issue description
      description: |
        Describe the issue in as much detail as possible.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files into it.
      placeholder: |
        Steps to reproduce:
        1. do thing
        2. observe behavior
        3. see error logs below
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you want to happen.
  - type: input
    id: node-version
    attributes:
      label: Node.js version
      description: Which version of Node.js are you using? Run `node --version` in your project directory and paste the output.
  - type: input
    id: os
    attributes:
      label: Operating system
      description: Which OS does your application run on?
  - type: dropdown
    id: priority
    attributes:
      label: Priority this issue should have
      description: Please be realistic. If you need to elaborate on your reasoning, please use the Issue description field above.
      options:
        - Low (slightly annoying)
        - Medium (should be fixed soon)
        - High (immediate attention needed)
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Other context
      description: Any other context, screenshots, or file uploads that help us understand your issue.
