blank_issues_enabled: false
contact_links:
  - name: Ask a question or discuss a topic
    url: https://github.com/rygent/Elvia/discussions
    about: Ask questions or discuss with other users in discussions.
  - name: Feature request
    url: https://github.com/rygent/Elvia/discussions/new?category=ideas
    about: Open a feature request in discussions.
  - name: Ask a question in Discord server
    url: https://discord.gg/FD5MMabf8Y
    about: Ask questions or discuss with other users in discord.
