name: Continuous Integration

on:
  push:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          HUSKY: '0'
      - name: Build packages (PR)
        if: ${{ github.event_name != 'push' }}
        run: pnpm exec turbo run build --filter="...[origin/${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref || 'main' }}]" --concurrency=3
      - name: Build packages (Push)
        if: ${{ github.event_name == 'push' }}
        run: pnpm exec turbo run build --filter="...[HEAD^1]" --concurrency=3
      - name: ESLint (PR)
        if: ${{ github.event_name != 'push' }}
        run: pnpm exec turbo run lint --filter="...[origin/${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref || 'main' }}]" --concurrency=3
      - name: ESLint (Push)
        if: ${{ github.event_name == 'push' }}
        run: pnpm exec turbo run lint --filter="...[HEAD^1]" --concurrency=3
      - name: Typecheck (PR)
        if: ${{ github.event_name != 'push' }}
        run: pnpm exec turbo run typecheck --filter="...[origin/${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref || 'main' }}]" --concurrency=3
      - name: Typecheck (Push)
        if: ${{ github.event_name == 'push' }}
        run: pnpm exec turbo run typecheck --filter="...[HEAD^1]" --concurrency=3
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
