name: Label Synchronization

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  syncing:
    name: Syncing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Synchronize
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
